Try setting up a separate DB reader instance for blazer
cds-snc/notification-terraform pull request #1063
Opened 2023-12-01 21:49 UTC by jzbahrai

# Summary | Résumé

We need a new reader instance for blazer, that is part of the notification DB, but won't be used by the application layer.

2023-12-08 17:43 UTC, ben851 requested changes
Can you also update the prod and dev terragrunt.hcl's for RDS?

2023-12-08 19:45 UTC, patheard commented on aws/common/vpc.tf
> +resource "aws_subnet" "notification-canada-ca-private-separate-db-reader" {
You'll also need to setup a [route table and route table association](https://github.com/cds-snc/notification-terraform/blob/22b8c11aa002a34a6defceb3a7e7c249546db11e/aws/common/vpc.tf#L130-L151) that points it to a NAT gateway in the same availability zone.

The code should be something like this I believe:
```hcl
resource "aws_route_table" "notification-canada-ca-private-db-reader_subnet" {
  vpc_id = aws_vpc.notification-canada-ca.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.notification-canada-ca[0].id
  }

  tags = {
    Name       = "Private Subnet Route Table for DB reader"
    CostCenter = "notification-canada-ca-${var.env}"
  }
}

resource "aws_route_table_association" "notification-canada-ca-private-db-reader" {
  subnet_id      = aws_subnet.notification-canada-ca-private-separate-db-reader.id
  route_table_id = aws_route_table.notification-canada-ca-private-db-reader_subnet.id
}
```

2023-12-08 19:46 UTC, patheard commented on aws/rds/rds.tf
> +  count                        = 1
You can get away without the `count` unless you're planning to add more of these in the future.  It's also fine to leave it if you'd prefer.

2023-12-08 19:47 UTC, patheard commented on aws/rds/rds.tf
> +  instance_class               = var.rds_instance_type
You could also probably get away with small DB instance types here if you wanted to save a bit of $$$.

2023-12-08 19:47 UTC, patheard commented on aws/rds/rds.tf
> +  # tfsec:ignore:AWS053 - Encryption for RDS Perfomance Insights should be enabled.
nit: you can remove this comment

2023-12-08 19:51 UTC, ben851 approved these changes
Approved in principal - you may need to add Pat's changes as well!

2023-12-15 20:13 UTC, patheard approved these changes

2024-01-19 15:32 UTC, closed without merging

2024-01-19 15:32 UTC, jzbahrai commented
closing this ticket as this doesnt work