Added an warn alarm for when the daily rate limit has been reached
cds-snc/notification-terraform pull request #108
Opened 2020-12-15 16:58 UTC by jimleroyer

## Changes

Added a warning alarm for when the daily rate limit has been reached.

## Issue

https://trello.com/c/62gscLJH/169-graph-the-services-going-over-the-daily-rate-limit

## Test 

* A similar alarm has been created in staging and has been tested. This is the infrastructure code to automate the alarm creation.
* Once this has been merged and deployed to staging, I will trigger the alarm manually with a test service.

2020-12-15 17:44 UTC, AntoineAugusti requested changes

2020-12-15 17:44 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +  alarm_description   = "The daily rate limit has been reached."
We've got a ton of various rate limits on Notify. Could you update slug/name/description to reflect that this is a daily rate limit for _services_?

2020-12-15 17:44 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "daily-rate-limit-error-1-minute-warning" {
Could you move this alarm to the other file? https://github.com/cds-snc/notification-terraform/blob/main/aws/eks/cloudwatch_log.tf Other log metric alarms are there

2020-12-15 17:44 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +  metric_name         = "over-daily-rate-limit"
You should be able to use `aws_cloudwatch_log_metric_filter.over-daily-rate-limit.name` after moving to the other file

2020-12-15 17:44 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +  threshold           = 1
This is not a very important alarm for now, what do you think about changing to period to 300s to evaluate this alarm less frequently?

2020-12-15 17:44 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +  treat_missing_data  = "notBreaching"
👍

2020-12-15 17:45 UTC, AntoineAugusti commented on aws/common/cloudwatch_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "daily-rate-limit-error-1-minute-warning" {
Sorry, wrong link https://github.com/cds-snc/notification-terraform/blob/main/aws/eks/cloudwatch_alarms.tf

2020-12-15 17:49 UTC, jimleroyer commented on aws/common/cloudwatch_alarms.tf
> +  alarm_description   = "The daily rate limit has been reached."
Shall we update the filter `over-daily-rate-limit` in the `LogMetrics` namespace too then?

2020-12-15 17:51 UTC, jimleroyer commented on aws/common/cloudwatch_alarms.tf
> +  threshold           = 1
Good with me.

2020-12-16 07:13 UTC, AntoineAugusti approved these changes
Thanks for setting up this alarm @jimleroyer! 👏 

Made a few minor suggestions, feel free to merge after incorporating these. I would be in favour of revisiting the log metric name as well to put a blatant _service_ keyword in there, if you could do that.

Please update the alarm sheet one last time just before merging 👍

2020-12-16 07:13 UTC, AntoineAugusti commented on aws/eks/cloudwatch_alarms.tf
> +  alarm_description   = "The daily rate limit has been reached."
```suggestion
  alarm_description   = "The daily rate limit has been reached for a service"
```

2020-12-16 07:13 UTC, AntoineAugusti commented on aws/eks/cloudwatch_alarms.tf
> +  alarm_name          = "daily-service-rate-limit-error-1-minute-warning"
```suggestion
resource "aws_cloudwatch_metric_alarm" "daily-service-rate-limit-error-5-minutes-warning" {
  alarm_name          = "daily-service-rate-limit-error-5-minutes-warning"
```

2020-12-16 07:13 UTC, AntoineAugusti commented on aws/eks/cloudwatch_alarms.tf
> +  namespace           = "LogMetrics"
You should be able to use the `namespace` attribute of `aws_cloudwatch_log_metric_filter.over-daily-rate-limit`

2020-12-16 14:57 UTC, jimleroyer commented on aws/eks/cloudwatch_alarms.tf
> +  namespace           = "LogMetrics"
Hmm it makes sense but it does not work. I am reverting back to the hardcoded value.

2020-12-16 16:25 UTC, merged