Setup the static site for staging and the lambda for prod
cds-snc/notification-terraform pull request #1087
Opened 2024-01-03 21:02 UTC by jzbahrai

# Summary | Résumé

Add workflows to setup the system_status lambda for production and the system_status_static_site for staging

2024-01-03 21:08 UTC, ben851 requested changes
Seems that we're missing the static site env folder and config... we'll need to add that or else the pipeline will crash

2024-01-03 21:08 UTC, ben851 commented on .github/workflows/merge_to_main_staging.yml
> +          cd env/staging/system_status_static_site
This folder doesn't seem to exist?

2024-01-03 21:18 UTC, jzbahrai commented on .github/workflows/merge_to_main_staging.yml
> +          cd env/staging/system_status_static_site
i totally forgot to add the terragrunt hcl files! thanks

2024-01-04 16:32 UTC, ben851 approved these changes

2024-01-04 16:32 UTC, ben851 commented on .github/workflows/terragrunt_plan_staging.yml
> +          terragrunt: "true"
```suggestion
          terragrunt: "true"
          skip-conftest: "true"
```

2024-01-04 16:32 UTC, ben851 commented on .github/workflows/terragrunt_plan_production.yml
> +          terragrunt: "true"
```suggestion
          terragrunt: "true"
          skip-conftest: "true"
```

2024-01-04 16:34 UTC, merged