feat: bind critical alarms to opsgenie via sns topic
cds-snc/notification-terraform pull request #111
Opened 2020-12-17 05:53 UTC by dorianjp

**Issue**
https://trello.com/c/p8A8pAKS/187-set-up-cloudwatch-to-opsgenie-integration-in-production

closes #104 

In order to forward critical alarms via sns to opsgenie, a topic subscription was added.
Set to create in production only when env var PRODUCTION_CLOUDWATCH_OPSGENIE_ALARM_WEBHOOK is set.

Additionally all critical alarms are set to hit the same sns topic once they arrive to ok state.

2020-12-17 09:01 UTC, AntoineAugusti requested changes
Great work! A few minor things before approving the PR

2020-12-17 09:01 UTC, AntoineAugusti commented on .github/workflows/merge_to_main_production.yml
> +  TF_VAR_cloudwatch_opsgenie_alarm_webhook: ${{ secrets.PRODUCTION_CLOUDWATCH_OPSGENIE_ALARM_WEBHOOK }}
Added the appropriate secret

2020-12-17 09:01 UTC, AntoineAugusti commented on aws/common/sns.tf
> +  depends_on = [var.cloudwatch_opsgenie_alarm_webhook]
This line is not needed because Terraform will be able to infer the dependency as this variable is already used in the same block

2020-12-17 09:01 UTC, AntoineAugusti commented on aws/common/sns.tf
> +  raw_message_delivery = false
Can you run `make fmt` to align all these equal signs?

2020-12-17 16:44 UTC, dorianjp commented on aws/common/sns.tf
> +  raw_message_delivery = false
Done, FYI all the quotations throughout the codebase were also added by terraform/terragrunt when this ran.

2020-12-17 16:44 UTC, dorianjp commented on aws/common/sns.tf
> +  depends_on = [var.cloudwatch_opsgenie_alarm_webhook]
Removed, thx.

2020-12-17 19:04 UTC, AntoineAugusti approved these changes
Awesome, thanks!

2020-12-17 19:53 UTC, merged

2020-12-18 09:20 UTC, AntoineAugusti commented
@dorianjp You can prepare a production bump to the latest version to release this 👍