feat: Added Terraform config for an Elasticache Redis single instance cluster
cds-snc/notification-terraform pull request #124
Opened 2020-12-24 00:25 UTC by jimleroyer

# Summary | Résumé

[Following this ticket](https://trello.com/c/Hb6ijLTD/202-use-aws-elasticache-as-our-redis-instance), we want to switch from a self managed Redis instance to an AWS Elasticache Redis instance.

# Test instructions | Instructions pour tester la modification

_To follow..._

# Help requested | Aide requise

_To follow..._

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

_To follow..._

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2020-12-24 00:58 UTC, maxneuvians commented
Just as an aside I have found that you need to bind resource dependent security groups into the main EKS security group, otherwise the EKS cluster has no way to communicate with the resource. We had this issue with RDS https://github.com/cds-snc/notification-terraform/blob/main/aws/rds/rds.tf#L48-L50 and the ALB https://github.com/cds-snc/notification-terraform/blob/main/aws/eks/alb.tf#L11. This means that the EKS security group needs to exist before you can provision the redis cluster. This means you may need to take it out of `common` and write a new elasticache module like the `rds` one.

2020-12-24 01:01 UTC, jimleroyer commented
Thank for the heads up omniscient @maxneuvians . I will put this into a different module then. 👏

2020-12-24 01:08 UTC, maxneuvians commented
As mentioned ideally elasticache would have its own security group and you would just allow inbound/outbound traffic to the EKS one. Somehow it never really worked, might just need to dig a little deeper.

2021-01-04 14:34 UTC, AntoineAugusti requested changes
Good work 👏 

A few things to update before merging the PR

2021-01-04 14:34 UTC, AntoineAugusti commented on aws/elasticache/elasticache.tf
> +    maintenance_window   = "thu:04:00-thu:05:00"
(You can put a comment on your PR next time if you're not sure of something in the code 👍 )

Picking a different day for the maintenance window seems like a good idea! Is it possible to subscribe to some maintenance events to get a heads up before?

It's possible for RDS https://github.com/cds-snc/notification-terraform/blob/8a859b0028597f6a90a115edaefc6d85a54536a6/aws/rds/rds.tf#L65-L79

2021-01-04 14:34 UTC, AntoineAugusti commented on aws/elasticache/elasticache.tf
> +    # willing to do the upgrade in this dev iteration. [3]
We don't use strange features of Redis so I think we're fine with changing versions now. Can you pick the latest available version on AWS?

2021-01-04 14:34 UTC, AntoineAugusti commented on aws/elasticache/elasticache.tf
> +    cluster_id           = "notification-cluster-cache"
```suggestion
    cluster_id           = "notification-canada-ca-${var.env}-cluster-cache"
```
I think we put the env in all our names

2021-01-04 14:34 UTC, AntoineAugusti commented on env/production/common/terragrunt.hcl
> +  sns_monthly_spend_limit  = 10000
Can you run a `make fmt`? I think this space should not be here

2021-01-04 14:34 UTC, AntoineAugusti commented on env/staging/elasticache/terragrunt.hcl
> +  sns_alert_warning_arn     = dependency.common.outputs.sns_alert_warning_arn
I don't think this variable is used at the moment

2021-01-04 14:34 UTC, AntoineAugusti commented on env/production/elasticache/terragrunt.hcl
> +  sns_alert_warning_arn     = dependency.common.outputs.sns_alert_warning_arn
I don't think this is used

2021-01-04 14:34 UTC, AntoineAugusti commented on aws/elasticache/elasticache.tf
> +    num_cache_nodes      = 1
Can you put this in a variable?

2021-01-04 17:28 UTC, jimleroyer commented on aws/elasticache/elasticache.tf
> +    maintenance_window   = "thu:04:00-thu:05:00"
A search for the equivalent feature was not successful from my side, even though it does exist for redshift and other tech. I am skeptical it really is not there in Terraform as support [exists in AWS](https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ElastiCacheSNS.html) and it seems it is not mentioned in the [Terraform issue tracker](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+%22elasticache%22+event+). I will probably open an issue myself and see what is the reply.

Would there be any other way so manually subscribe to the events and publish these on sns?

2021-01-04 20:55 UTC, AntoineAugusti commented on aws/elasticache/elasticache.tf
> +  parameter_group_name = "default.redis4.0"
```suggestion
  parameter_group_name = "default.redis6.x"
```

2021-01-04 20:55 UTC, AntoineAugusti commented on env/staging/elasticache/terragrunt.hcl
> +    sns_alert_warning_arn = ""
This is not used

2021-01-04 21:23 UTC, jimleroyer commented on env/staging/elasticache/terragrunt.hcl
> +    sns_alert_warning_arn = ""
Just removed..

2021-01-05 15:16 UTC, AntoineAugusti approved these changes
This can be shipped in staging 👍 

Before merging, can you remove changes you made to these files:
- .github/workflows/merge_to_main_production.yml
- env/production/elasticache/terragrunt.hcl

These files are fine but we can't release them now. If we merge as is, it'll try to deploy to production with the current `INFRASTRUCTURE_VERSION` tag. This tag does not include the new Elasticache changes so we'll need to:
- merge this PR, this will create a new tag
- if this is okay, release to production by bumping the tag and making the changes you just proposed to these files

2021-01-06 13:05 UTC, AntoineAugusti approved these changes
🚢

2021-01-06 18:41 UTC, merged