Add script to create pinpoint pools
cds-snc/notification-terraform pull request #1246
Opened 2024-04-10 19:25 UTC by sastels

# Summary | Résumé

Can't do this with terraform nor CloudFormation yet 😞 
This script hasn't been added to any merge / release automation.

## Related Issues | Cartes liées

* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/286

# Test instructions | Instructions pour tester la modification

Can run the script somewhere, just clean up after yourself. 

# Release Instructions | Instructions pour le déploiement

None.

# Reviewer checklist | Liste de vérification du réviseur

- [ ] This PR does not break existing functionality.
- [ ] This PR does not violate GCNotify's privacy policies.
- [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
- [ ] This PR does not significantly alter performance.
- [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

2024-04-16 19:59 UTC, ben851 requested changes
This is an amazing amount of work! Nice!

Can we move the cloudwatch logs, and iam from common into the pinpoint directory? That way everything related to pinpoint is in one spot (and you don't have to depend on common and outputs as a bonus!)

2024-04-16 19:59 UTC, ben851 commented on aws/pinpoint_to_sqs_sms_callbacks/lambda.tf
> +data "aws_sqs_queue" "delivery-receipts" {
Do we have this value somewhere else? I think in the sqs section? Would be good to have it referencing that in case we change it down the line.

2024-04-16 20:00 UTC, ben851 commented on aws/common/cloudwatch_log.tf
> +}
We don't do this yet, but we should add a card to get this done on all of the logs.

2024-04-16 22:06 UTC, sastels commented on aws/pinpoint_to_sqs_sms_callbacks/lambda.tf
> +data "aws_sqs_queue" "delivery-receipts" {
yesss we can pull it from common 👍

2024-04-16 22:12 UTC, sastels commented on aws/ecr/images.tf
> -    command = "docker build -t ${aws_ecr_repository.sns_to_sqs_sms_callbacks.repository_url}:bootstrap -f /var/tmp/notification-lambdas/sesemailcallbacks/Dockerfile /var/tmp/notification-lambdas"
Noticed this typo

2024-04-17 15:29 UTC, ben851 requested changes
It's a cool idea to keep this contained with the lambda function, but it won't work as is because on a new environment apply, the lambda module will fail because there is no dependency relationship between the module and these (so the module will try and run before the docker image exists).

If you add a depends_on to the module, it won't work either because the dependency resource only creates when bootstrap is set to true.

You could try a conditional dependency - I'm not sure that's a thing... but something like:

depends_on = [var.bootstrap ? null_resource.push_pinpoint_to_sqs_sms_callbacks_docker_image : null ]

no idea if that will work though... If it doesn't, it's probably easiest to just move this file back to the ecr directory.

Also, does the create_pinpoint_pools.sh script have to be run before deploy? If that's the case, can we add it as a null_resource that gets executed if bootstrap = true?

2024-04-17 15:35 UTC, sastels commented
> Also, does the create_pinpoint_pools.sh script have to be run before deploy? If that's the case, can we add it as a null_resource that gets executed if bootstrap = true?

no, in fact we need to have the terraform done (at least we need the iam role and cloudwatch receipt log groups).

2024-04-22 15:46 UTC, ben851 approved these changes
LGTM!

2024-04-22 17:12 UTC, merged