add new sns topic and slack integration
cds-snc/notification-terraform pull request #145
Opened 2021-01-14 02:35 UTC by dorianjp

* Added new topic "notification-canada-ca-alert-general"
* Re-assigned to new topic:
  * aws_health
  * rds
* Added new slack module "notify_slack_general"
  * bind to new general sns topic
  * new env vars for webhook and channel, copied values similar to existing slack integrations

2021-01-14 02:38 UTC, dorianjp commented
![](https://github.trello.services/images/mini-trello-icon.png) [SNS warning Topic should only be used by Alarms](https://trello.com/c/4e58AlOx/178-sns-warning-topic-should-only-be-used-by-alarms)

2021-01-14 02:54 UTC, dorianjp commented
@AntoineAugusti I left email out as the email subscription protocol is [unsupported](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_subscription#email) unless you have something else in mind to send the email, or just do it this way regardless. I thought about using notify via https, but that wouldn't work with some of the failure scenarios, after-all notify would be potentially down 😄

2021-01-14 14:04 UTC, AntoineAugusti requested changes

2021-01-14 14:04 UTC, AntoineAugusti commented on .github/workflows/merge_to_main_production.yml
> +  TF_VAR_slack_channel_general_topic: "notification-ops"
These changes are fine, but you need to submit them later. If you submit them now, the production CI job will try to assign these variables in the codebase @ version 0.54.0 as defined in `INFRASTRUCTURE_VERSION` a few lines before and these variables don't exist yet.

You'll need to submit these changes when bumping the production version.

2021-01-14 14:04 UTC, AntoineAugusti commented on aws/rds/variables.tf
> +variable "sns_alert_general_arn" {
You'll need to change the file `env/staging/rds/terraform.hcl` to map this variable to the appropriate value in the `common` module

2021-01-14 14:04 UTC, AntoineAugusti commented on aws/eks/variables.tf
> +variable "sns_alert_general_arn" {
You'll need to change the file `env/staging/eks/terraform.hcl` to map this variable to the appropriate value in the `common` module

2021-01-14 14:05 UTC, AntoineAugusti commented
@dorianjp Yeah, the only way to send alerts via email at the moment would be to have an SNS subscription to a Lambda and then you write a Lambda to send an email with SES or Notify so you can leave that out for now

2021-01-15 06:42 UTC, dorianjp commented on .github/workflows/merge_to_main_production.yml
> +  TF_VAR_slack_channel_general_topic: "notification-ops"
Sounds good, took the prod vars out for now.

2021-01-15 06:42 UTC, dorianjp commented on aws/common/slack.tf
> +  depends_on = [aws_sns_topic.notification-canada-ca-alert-general]
Done

2021-01-15 06:43 UTC, dorianjp commented on aws/eks/variables.tf
> +variable "sns_alert_general_arn" {
Assuming terragrunt.hcl?
Done

2021-01-15 06:43 UTC, dorianjp commented on aws/rds/variables.tf
> +variable "sns_alert_general_arn" {
+1

2021-01-15 21:49 UTC, dorianjp commented
@AntoineAugusti , I have a few changes I will need to push on the next 2 PRs due to the CI failing on expected resources:
* TF_VARs discussed above (during prod push only)
* slack.tf -> the definition of the general alerting module (aws plan looks for the sns topic prematurely when this is in)
* terragrunt.hcl (eks and rds) adding the input bindings

2021-01-18 13:24 UTC, AntoineAugusti approved these changes
LGTM.

Please make sure that the commit message will be prefixed with `feat:` when merging your PR so that a new tag will be created.

Looking forward to the other PRs 👍

2021-01-18 19:38 UTC, merged