Enabled Athena with a dedicated S3 bucket
cds-snc/notification-terraform pull request #156
Opened 2021-01-18 23:46 UTC by jimleroyer

# Summary | Résumé

Let's have more tools to investigate issues around load balancers. AWS Athena can help us with that. [The trello card is here](https://trello.com/c/L775pbnO/243-enable-athena-engine-to-investigate-recent-load-balancers-issue).

# Test instructions | Instructions pour tester la modification

We'll log into the AWS management console and see if AWS Athena is enabled and working with queries against load balancers.

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2021-01-18 23:48 UTC, jimleroyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable Athena engine to investigate recent load balancers' issue](https://trello.com/c/L775pbnO/243-enable-athena-engine-to-investigate-recent-load-balancers-issue)

2021-01-18 23:59 UTC, jimleroyer commented on aws/common/athena.tf
> +      encryption_configuration {
I've put some encryption configuration and went with the easiest option to use:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/athena_workgroup#encryption_configuration

Tell me if we want encryption and if that's the right option to use.

2021-01-19 13:12 UTC, AntoineAugusti requested changes

2021-01-19 13:12 UTC, AntoineAugusti commented on aws/common/athena.tf
> +}
Can you move S3 buckets to `s3.tf`?

2021-01-19 13:12 UTC, AntoineAugusti commented on aws/common/athena.tf
> +      days = 7
👍

2021-01-19 13:12 UTC, AntoineAugusti commented on aws/common/athena.tf
> +      days = 90
👍

2021-01-19 13:12 UTC, AntoineAugusti commented on aws/common/athena.tf
> +resource "aws_athena_database" "notification_athena" {
Can you add encryption with `SSE_S3`?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/athena_database#encryption_option

2021-01-19 13:12 UTC, AntoineAugusti commented on aws/common/athena.tf
> +resource "aws_athena_workgroup" "notification_athena_workgroup" {
We may be able to delete the workgroup. After [reading the documentation](https://docs.aws.amazon.com/athena/latest/ug/user-created-workgroups.html), we already have a primary workgroup we cannot delete and it seems like this is enough for us.

> By default, each account has a primary workgroup and the default permissions allow all authenticated users access to this workgroup. The primary workgroup cannot be deleted.

Can you take a look at the doc and confirm you understand the same thing?

2021-01-19 14:52 UTC, jimleroyer commented on aws/common/athena.tf
> +      days = 90
I will change to 7 to match with the previous one.

2021-01-19 15:06 UTC, jimleroyer commented on aws/common/athena.tf
> +resource "aws_athena_workgroup" "notification_athena_workgroup" {
That makes sense.. It seems like workgroup is a feature added to have independent sandbox to manage queries, finance, quotas, permissions... we'd be good with the default in our case.

2021-01-19 16:03 UTC, AntoineAugusti approved these changes
Made a suggestion to delete an extra `depends_on`

LGTM, keep me posted if it works in staging

2021-01-19 16:03 UTC, AntoineAugusti commented on aws/common/athena.tf
> +  depends_on = [aws_s3_bucket.athena_bucket]
```suggestion
```
You should be able to leave this out as you're already referencing this resource in the bucket `field`

2021-01-19 16:32 UTC, jimleroyer commented on aws/common/athena.tf
> +  depends_on = [aws_s3_bucket.athena_bucket]
Ok got it

2021-01-19 16:40 UTC, merged