feat: add terraform for aws lambda deployment of api
cds-snc/notification-terraform pull request #289
Opened 2021-08-18 21:00 UTC by smcmurtry

# Summary | Résumé

So far I have borrowed some code that looked relevant from here: https://github.com/cds-snc/scan-websites/tree/main/terragrunt/aws/api

I'm not sure what I'm doing so I am putting this up as a draft for now.

2021-08-19 15:34 UTC, smcmurtry commented on aws/common/lambda.tf
> +      ADMIN_CLIENT_SECRET =
Do I need to create an inputs.tf file (like [this](https://github.com/cds-snc/scan-websites/blob/main/terragrunt/aws/api/inputs.tf)) for all of these environment variables?

2021-08-19 15:47 UTC, smcmurtry commented on aws/common/lambda.tf
> +      ADMIN_CLIENT_SECRET =
Okay I think I should just add entries to aws/common/variables.tf (or perhaps move things to a new folder aws/lambda/?) like this:
```
variable "admin_client_secret" {
  type = string
  sensitive   = true
}
```

2021-08-19 16:08 UTC, patheard commented on aws/common/lambda.tf
> +      ADMIN_CLIENT_SECRET =
Yup, that's correct - Terraform will look in a few places to try and [assign variable values](https://www.terraform.io/docs/language/values/variables.html#assigning-values-to-root-module-variables).  In the case of your pipeline, it's using the `TF_VAR_` environment var method.

So in your case, you'd just need to make sure there was a `TF_VAR_admin_client_secret` in scope and the value would get set during the `terraform plan/apply` commands.

One other note about needing an `inputs.tf` file.  That's just convention around the name.  You could add the `variable` definition block to any `.tf` file that's in the same Terraform module and it would get correctly recognized as a variable.

2021-08-19 16:39 UTC, patheard reviewed
Alrighty, had a look and I've got some comments/suggestions.  Happy to chat if you want to go over anything!

2021-08-19 16:39 UTC, patheard commented on aws/common/ecr.tf
> +  # checkov:skip=CKV_AWS_51:The :latest tag is used in Staging
This will need to change to a tfsec style ignore comment:
```
# tfsec:ignore:AWS078
```
We're using [checkov](https://github.com/bridgecrewio/checkov) on the scan-websites project which is why we've got a different ignore comment style.

2021-08-19 16:39 UTC, patheard commented on aws/common/api_gateway.tf
> +}
You'll also need to add the custom API gateway domain to this, which will need a block like so:
https://github.com/cds-snc/covid-alert-metrics-terraform/blob/main/aws/api_gateway/metrics_gateway.tf#L13-L27

You may be able to use the existing Notify staging ACM certificate for this - it depends on how it's setup.  If it's a wildcard cert for `*.notification.staging.cdssandbox.xyz` you can use it.

2021-08-19 16:39 UTC, patheard commented on aws/common/lambda.tf
> +  image_uri    = "${aws_ecr_repository.api.repository_url}:latest"
Note that this will fail the first time you try to `terraform apply` since the ECR registry won't exist yet.  Just one of the sequencing gotchas around working with Terraform.

Nothing you need to change though - just one of those "run it again" situations.

2021-08-19 16:39 UTC, patheard commented on aws/common/api_gateway.tf
> +  }
Check the `triggers` block on this example:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment#terraform-resources

This gives you an implicit dependency on all those resources, which will make sure that:
1. If any change, the API is redeployed; and
2. The API deployment resource won't be created until the listed trigger resources are created.

```hcl
resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    # NOTE: The configuration below will satisfy ordering considerations,
    #       but not pick up all future REST API changes. More advanced patterns
    #       are possible, such as using the filesha1() function against the
    #       Terraform configuration file(s) or removing the .id references to
    #       calculate a hash against whole resources. Be aware that using whole
    #       resources will show a difference after the initial implementation.
    #       It will stabilize to only change when resources change afterwards.
    redeployment = sha1(jsonencode([
      aws_api_gateway_resource.example.id,
      aws_api_gateway_method.example.id,
      aws_api_gateway_integration.example.id,
    ]))
  }

  lifecycle {
    create_before_destroy = true
  }
}

```

This is probably something we should add to our scan-websites code 😉

2021-08-19 16:39 UTC, patheard commented on aws/common/api_gateway.tf
> +resource "aws_api_gateway_stage" "api" {
It'd be helpful to create an `access_log` block on this resource, similar to what I've [done on this project](https://github.com/patheard/aws-fastapi-lambda/blob/main/infra/modules/api-gateway/api-gateway.tf#L40-L43).

It'll also clear up the other `tfsec` warning you're getting on the PR.

2021-08-19 16:39 UTC, patheard commented on aws/common/lambda.tf
> +  role    = aws_iam_role.api.arn
I'm not seeing this role?  You'll need to define a role that can be assumed by the Lambda function and lets it interact with the VPC.  Here's an [example of how I've done it](https://github.com/patheard/aws-fastapi-lambda/blob/main/infra/modules/api-gateway/lambda.tf#L35-L43).

2021-09-08 12:31 UTC, patheard requested changes
Looking good Steve!  I've added more review comments - if anything's not clear, let me know and we can chat about it.

2021-09-08 12:31 UTC, patheard commented on .github/workflows/merge_to_main_staging.yml
> +
Can you add this same job step to [.github/workflows/pull_requests.yml](https://github.com/cds-snc/notification-terraform/blob/feature/terraform-for-lambda-api/.github/workflows/pull_requests.yml).  That'll let us see the plan changes for the new Terraform.

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/iam.tf
> +      "logs:CreateLogGroup",
You don't need this since the Terraform already creates the log group.  

It doesn't hurt to have it, but it can lead to weird situations if you ever destroy the infrastructure, buffered logs re-create the log group unexpectedly, which causes the next `terraform apply` to fail with a "Log group already exists" error.

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/iam.tf
> +      "*"
This works, but for better security, you can scope it down the target log group ARN:
```hcl
aws_cloudwatch_log_group.api_gateway_log_group.arn
```

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/iam.tf
> +}
I'd recommend sticking with the `data "aws_iam_policy_document" "policy_name"` approach you've used above just for consistency.  

There's nothing wrong, Terraform-wise, with this approach though.

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/lambda.tf
> +    subnet_ids = var.vpc_private_subnets
nit: I'm not sure if your pull request workflow has a Terraform format check, but this would fail if yes (it would still run fine though).  

An easy way to format everything up nicely is to run this at the top level of your `*.tf` folder:
```sh
terraform fmt -recursive
```

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/lambda.tf
> +}
Why the two `aws_lambda_permission` resources?

2021-09-08 12:31 UTC, patheard commented on aws/lambda-api/variables.tf
> +  sensitive = true
nit: same comment about `terraform fmt`

2021-09-08 12:31 UTC, patheard commented on env/staging/lambda-api/terragrunt.hcl
> +      "subnet-0af8b8402f1d605ff",
You can also set these as blank strings in the mock output and it'll still work.  There's no issue having a non-empty mock value specified though.

2021-09-08 12:31 UTC, patheard commented on env/staging/lambda-api/terragrunt.hcl
> +  mock_outputs_allowed_terraform_commands = ["validate"]
I usually set this to the full list of TF commands that might need mocked output:
```hcl
mock_outputs_allowed_terraform_commands = ["init", "fmt", "validate", "plan", "show"]
```

2021-09-08 12:31 UTC, patheard commented on env/staging/lambda-api/terragrunt.hcl
> +  vpc_private_subnets       = dependency.common.outputs.vpc_private_subnets
There's no harm adding your non-secret variable values here - I find it makes it easier to maintain, but it's a preference thing - always using `TF_VAR_variable_name` is totally legit.
```hcl
aws_pinpoint_region = "us-west-2"
redis_enabled       = "1"
```

2021-09-10 17:29 UTC, sastels commented on .github/workflows/merge_to_main_staging.yml
> +
Added to the end:
```
      - name: Plan aws/lambda-api
        run: |
          cd env/${{env.TARGET_ENV_PATH}}/lambda-api
          ../../../bin/terragrunt plan --terragrunt-non-interactive
```

2021-09-10 18:14 UTC, sastels commented on aws/lambda-api/iam.tf
> +}
@patheard I moved it into the `data "aws_iam_policy_document" "api_policies"` block above - does this make sense, or would it be better to have its own block?

2021-09-10 18:39 UTC, sastels commented on aws/lambda-api/lambda.tf
> +}
🤷‍♂️  Steve M works in mysterious ways.
Smoke tests all run without it though. I think it might have something to do with concurrency.

2021-09-14 18:02 UTC, patheard commented on aws/lambda-api/lambda.tf
> +  image_uri    = "${aws_ecr_repository.api.repository_url}:latest"
One minor comment - when you move this to prod, you'll want to switch away from `latest` to a defined image tag.  Usually I do it as a variable in the `terragrunt.hcl` but you can also do it with a manifest style approach.

2021-09-14 18:05 UTC, patheard commented on aws/lambda-api/iam.tf
> +}
Yup, totally makes sense in the same block.  

There's actually a limit to the number of policies that can be attached to a role (10 I think) and so having multiple `statement` elements in a single policy is a way to work around this limit.

2021-09-14 18:06 UTC, patheard commented on aws/lambda-api/lambda.tf
> +}
`¯\_(ツ)_/¯`

I'd vote for removing it and seeing if anything breaks.

2021-09-14 18:17 UTC, patheard commented on .github/workflows/pull_requests.yml
> +          ../../../bin/terragrunt plan --terragrunt-non-interactive
Something you could try (certainly not required) is to switch to the [cds-snc/terraform-plan](https://github.com/cds-snc/terraform-plan) GitHub action.  This will run `terraform plan` and output the plan as a comment on the PR.  

To use it, you'd just need to change the GitHub workflow like so:
1. [Install Terragrunt globally](https://github.com/cds-snc/platform-mvp-ircc/blob/e23f953ec1414cd3755bdf1665fbe295defef664/.github/workflows/terragrunt-plan-prod.yml#L52-L57) in the workflow.
2. [Use the action for each folder](https://github.com/cds-snc/platform-mvp-ircc/blob/e23f953ec1414cd3755bdf1665fbe295defef664/.github/workflows/terragrunt-plan-prod.yml#L91-L99) (the `if` piece isn't required).

2021-09-14 18:17 UTC, patheard approved these changes
Looks good!  I had a few non-blocking comments, but I'd say you're good to merge!

When you're back from vacation, lets talk next steps again.

2021-09-23 15:39 UTC, sastels commented on .github/workflows/pull_requests.yml
> +          ../../../bin/terragrunt plan --terragrunt-non-interactive
Thinking a bit more about it, I think we can do this in another PR.

2021-09-23 18:00 UTC, merged

2021-09-23 23:16 UTC, jimleroyer commented on aws/lambda-api/api_gateway.tf
> +    Environment = "staging"
Should we replace the environment hard coded value with the variable? or it's unrelated to the environment in which Notify runs?

2021-09-23 23:24 UTC, jimleroyer commented on env/staging/lambda-api/terragrunt.hcl
> +  api_image_tag             = "latest"
I assume we'll need to come up with a release strategy that will write a value with a specific SHA ID to specify the image tag, is this right? I wonder because in case we want to revert and not use the latest available image in the image repository.

2021-09-23 23:25 UTC, jimleroyer commented on aws/lambda-api/lambda.tf
> +}
Beautiful

2021-09-23 23:28 UTC, jimleroyer reviewed
Excellent work Steves~! 🙌

2021-09-28 22:30 UTC, sastels commented on aws/lambda-api/api_gateway.tf
> +    Environment = "staging"
Hrm, yeah, there’s a variable `var.env` that we should probably use here.

2021-09-28 22:33 UTC, sastels commented on env/staging/lambda-api/terragrunt.hcl
> +  api_image_tag             = "latest"
This is the staging config so this is probably good. Reverting api would change latest to point to the new reverted version. The prod version of this file should be different. And somehow use the manifest repo?

2021-09-28 22:35 UTC, sastels commented on env/staging/lambda-api/.terraform.lock.hcl
> +    "zh:ee65f3d2c13653e0828222a63fb832f98e9835b84443eeca00ce36ae39783c08",
This is a good point… @patheard should this be here? I thought I read somewhere that our state was stored  in AWS?

2021-09-29 12:48 UTC, patheard commented on env/staging/lambda-api/.terraform.lock.hcl
> +    "zh:ee65f3d2c13653e0828222a63fb832f98e9835b84443eeca00ce36ae39783c08",
Generally yes, but your project is bit odd in this.  The `.terraform.lock.hcl` locks the versions of the providers/modules that are installed by the `terraform init` command (like the `package-lock.json` file in a Node.js project).  

The first time `terraform init` runs, it checks the version constraints specified for the providers/modules and installs the ones that match.  It then creates `.terraform.lock.hcl` to specify exactly which version of each provider/module was installed.

The next time you run `terraform init`, instead of using the version constraints, it installs the exact version from `.terraform.lock.hcl`.  In other words, it pins versions to have consistent installs and `terraform plan/apply` runs.

Your project doesn't do this because the `terraform init` command is always run in GitHub Actions, so the `.terraform.lock.hcl` file gets generated, but never committed to the repo.  As a result, there's a small chance that at some point in the future you could end up with a broken `terraform plan/apply` run because a provider or module upgrades, but still matches your version constraints.

Personally I would say each of your modules should have a `.terraform.lock.hcl` committed.

2021-09-29 18:53 UTC, jimleroyer commented on env/staging/lambda-api/terragrunt.hcl
> +  api_image_tag             = "latest"
Ok get it.. and yeah, ideally if we could leverage the manifest repository or have something similar, it would be great.