Fix alarm when no data
cds-snc/notification-terraform pull request #294
Opened 2021-09-13 17:53 UTC by jzbahrai

# Summary | Résumé

At the beginning of the month, the data on each alarm resets. Until the service does work, no data gets collected. This triggers a false alarm in our slack channels. We want this alarm to not page us if there isn't enough data, this PR does that. 

https://trello.com/c/rn2qi3dq/686-make-sure-sns-spending-alarms-handle-missing-states

# Test instructions | Instructions pour tester la modification
- Unsure how to test this in staging.

2021-09-15 13:55 UTC, jimleroyer approved these changes
LGTM!

2021-09-15 13:55 UTC, jimleroyer requested changes
Oh forgot one tiny detail, will add a new comment.

2021-09-15 13:56 UTC, jimleroyer commented on aws/common/cloudwatch_alarms.tf
> +  treat_missing_data  = "notBreaching"
This is the critical alarm but we also need to update the warning alarm at line #20.

2021-09-15 20:10 UTC, jzbahrai commented on aws/common/cloudwatch_alarms.tf
> +  treat_missing_data  = "notBreaching"
done!

2021-09-16 14:20 UTC, jimleroyer approved these changes
:shipit:

2021-09-16 15:53 UTC, merged