bump infrastructure to 0.105.9
cds-snc/notification-terraform pull request #314
Opened 2021-11-02 18:38 UTC by sastels

# Summary | Résumé

Note that prod was update when `merge_to_main_production.yml` was changed in #308. So prod is at v0.105.7

Changes to production since 0.105.5:

[add a user with ECR push permissions](https://github.com/cds-snc/notification-terraform/pull/306) (currently in prod)
[add domain name for api lambda's api gateway](https://github.com/cds-snc/notification-terraform/pull/307)

# Test instructions | Instructions pour tester la modification

# Help requested | Aide requise

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-11-03 01:50 UTC, sastels commented
The prod plan isn’t showing any additions - we need to add `base` to the filter set to the infrastructure tag. See https://github.com/dorny/paths-filter

2021-11-03 16:16 UTC, sastels commented
Can't use `base` with a pull request:
```
Warning: 'base' input parameter is ignored when action is triggered by pull request event
```
😞 
Will switch to not filtering at all. This might be the better approach anyway, as the merge_to_production isn't doing any filtering.

2021-11-03 16:53 UTC, jimleroyer requested changes
It might have been better to decouple the infrastructure bump from changes into our workflow, as a best practice to decouple releases vs infra code changes.

2021-11-03 16:53 UTC, jimleroyer commented on .github/workflows/terragrunt_plan_production.yml
> -
Why do we want to remove these filters?

2021-11-03 17:30 UTC, sastels commented on .github/workflows/terragrunt_plan_production.yml
> -
ah, I should have explained better 👍 
It's because the filters compare this branch to `main`. Since this PR doesn't change any of the terraform code, everything will be filtered out and no plans will run. The use of `base` allows you to compare to another branch, but unfortunately is ignored in a pull request.

2021-11-03 17:36 UTC, sastels commented
> It might have been better to decouple the infrastructure bump from changes into our workflow, as a best practice to decouple releases vs infra code changes.

Yeah, this bothered me, but the workflow won't run unless the infrastructure version changes. But once we agree on the changes to the workflow, a good idea might be to move them to their own PR (where the changed prod workflow won't run but we can see what it will do here). Then after that PR merges, this one will just be changing the infrastructure version.

2021-11-03 18:12 UTC, sastels commented
👍 Moved the workflow change to #315

2021-11-04 19:43 UTC, jimleroyer approved these changes
👍

2021-11-05 17:45 UTC, sastels commented
It's complaining about variables changing in the production plan
```
              ~ "ADMIN_CLIENT_USER_NAME"         = (sensitive)
              ~ "ASSET_DOMAIN"                   = "assets.notification.canada.ca" -> ""
              ~ "ASSET_UPLOAD_BUCKET_NAME"       = "notification-canada-ca-production-asset-upload" -> ""
              ~ "CSV_UPLOAD_BUCKET_NAME"         = "notification-canada-ca-production-csv-upload" -> ""
              ~ "DOCUMENTS_BUCKET"               = "notification-alpha-canada-ca-document-download" -> ""
```
These variables were moved to the `terragrunt.hcl` files and shouldn't be in `terragrunt_plan_production.yml`

2021-11-05 18:41 UTC, merged