Update ENVs and define S3 bucket with permissions
cds-snc/notification-terraform pull request #317
Opened 2021-11-08 16:28 UTC by iokpala

# Summary | Résumé

To publish performance test results to s3 (for storage), this commit defines an s3 terraform script that reuses the SRE team's S3 terraform module [1].

Within is also defined aws_iam_policy that allow for CRUD activities [2],

Also within we have updated the environment variables and 

[1] github.com/cds-snc/terraform-modules?ref=v0.0.38//S3
[2] https://registry.terraform.io/modules/cloudposse/s3-bucket/aws/latest/examples/complete?tab=inputs

2021-11-08 17:09 UTC, jimleroyer commented on env/staging/performance-test/terragrunt.hcl
> +  aws_pinpoint_region         = "ca-central-1"
Good catch

2021-11-08 18:01 UTC, jimleroyer commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
Can we keep the same semantic around performance tests and rename these variables `PERF_TEST...` instead of `LOAD_TEST...`?

2021-11-08 18:19 UTC, iokpala commented on env/staging/performance-test/terragrunt.hcl
> +  aws_pinpoint_region         = "ca-central-1"
Cheers

2021-11-08 18:27 UTC, patheard requested changes
Looks like a good start!  Had some comments around how to get the Terraform plan working and how we can switch to just using the IAM policy change instead of AWS access and secret keys.

2021-11-08 18:27 UTC, patheard commented on aws/performance-test/lambda.tf
> +      AWS_SECRET_ACCESS_KEY                       = var.aws_secret_access_key
You should be able to get rid of these variables since you're using an IAM policy to grant access to the S3 bucket from the Lambda.

2021-11-08 18:27 UTC, patheard commented on aws/performance-test/variables.tf
> +}
You can get rid of this too since the common `env` variable should have the value you need.

2021-11-08 18:27 UTC, patheard commented on aws/performance-test/variables.tf
> +}
These can go as well - we'll rely on the IAM policy instead so you don't have to manage a new IAM user with an access key and secret.

2021-11-08 18:27 UTC, patheard commented on aws/performance-test/variables.tf
> +  description = "This helps identify aws access key."
nit: could you make the variable descriptions unique.

2021-11-09 10:22 UTC, iokpala commented on aws/performance-test/variables.tf
> +variable "aws_default_output" {
It refers to the putput format example text, json etc see https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output-format.html

2021-11-09 10:22 UTC, iokpala commented on aws/performance-test/variables.tf
> +  description = "This helps identify aws access key."
Will correct that

2021-11-09 10:25 UTC, iokpala commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
Yeah, well this is a continuation of the definition from the api repo.. See https://github.com/cds-snc/notification-api/blob/master/tests-perf/locust/locust-notifications.py#L36-L43 and https://github.com/cds-snc/notification-api/blob/89e6d832443d337c88b27f5a38a0e2eb12413bc3/tests-perf/ops/Dockerfile#L22-L30

2021-11-09 10:25 UTC, iokpala commented on aws/performance-test/variables.tf
> +  description = "This helps identify aws access key."
Will correct it

2021-11-09 10:25 UTC, iokpala commented on aws/performance-test/variables.tf
> +}
Absolutely

2021-11-09 10:26 UTC, iokpala commented on aws/performance-test/variables.tf
> +}
I defined this after getting an error that it was not declated.. Will take a look at common

2021-11-09 10:26 UTC, iokpala commented on aws/performance-test/lambda.tf
> +      AWS_SECRET_ACCESS_KEY                       = var.aws_secret_access_key
Will remove

2021-11-09 14:05 UTC, patheard commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
This is the line that's giving you grief in your `terraform plan`.  Unfortunately you can't reference variables within a `variable` block.

2021-11-09 16:42 UTC, jimleroyer commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
Yeah I see, so we are misaligned in there as well. The directory call these performance tests. The image in this PR calls these performance test. I would like to aim for one semantic to avoid confusion on what is what. What is your suggestion?

2021-11-09 16:47 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
So we'll have to concat the strings where it's used, right?

2021-11-09 16:47 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  description = "This helps identify performance test domain."
nitpick: `Identifies performance test domain` or `Performance test domain` might be better worded, as well for the other ones.

2021-11-09 16:47 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  description = "This helps identify aws access key."
Thanks for the explanation. This was the TF default I guess? as I see we dropped this variable?

2021-11-09 16:56 UTC, patheard commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
It just means you can't use the variable to set a `default` value here.  So yup, string concat if you're doing this in a `terragrunt.hcl` file, or just like so if you're using it in a `*.tf` file:
https://github.com/cds-snc/notification-terraform/blob/feature/publish-performance-test-results/aws/performance-test/s3.tf#L3

2021-11-09 17:42 UTC, iokpala commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
Yikes

2021-11-09 17:45 UTC, iokpala commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
I have xtried a few things and nothing really worked.. so will just go with a static value

2021-11-09 18:18 UTC, patheard commented on aws/performance-test/s3.tf
> +      "${aws_s3_bucket.reliability_file_storage.arn}/*"
Missed this the last time round - this will need to be updated to the ARN of the performance bucket like so:
```hcl
module.notify_performance_test_results.s3_bucket_arn,
"${module.notify_performance_test_results.s3_bucket_arn}/*"
```

2021-11-09 18:20 UTC, iokpala commented on aws/performance-test/s3.tf
> +      "${aws_s3_bucket.reliability_file_storage.arn}/*"
Thanks will update it

2021-11-09 19:48 UTC, jimleroyer commented on aws/performance-test/s3.tf
> -  billing_tag_value = "notification-canada-ca-${var.env}"
Can we not keep this variable?

2021-11-09 19:50 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-staging"
We'd remove the env variable (and static reference) from this and concat it where it is used.

2021-11-09 19:50 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
I don't think that @patheard meant to go full static values, but rather to use the variables in places to concat these. I can show you in places where we do it in the TF code if you want.

2021-11-09 21:49 UTC, iokpala commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-staging"
@patheard  Would it be possible to concat this from the terraform modules??

2021-11-10 14:48 UTC, patheard commented on aws/performance-test/s3.tf
> +  bucket_name       = "notify-performance-test-results-staging"
These can become:
```hcl
  bucket_name       = "notify-performance-test-results-${var.env}"
  billing_tag_value = "notification-canada-ca-${var.env}"
```

2021-11-10 14:51 UTC, iokpala commented on aws/performance-test/s3.tf
> +  bucket_name       = "notify-performance-test-results-staging"
Thanks Pat.. I have added it back

2021-11-10 15:28 UTC, jimleroyer commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
@iokpala You asked for another review round but you have not replied to me on this yet.

2021-11-10 15:50 UTC, iokpala commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
I see merits in this Would it be Ok to have this request in a new PR?? I ask this because the `LOAD_TEST` prefix is already being used.. My appeal is that this be done in uniformity given previous acceptance

2021-11-10 15:52 UTC, iokpala commented on aws/performance-test/variables.tf
> +  description = "This helps identify performance test domain."
I beg to differ as this appears deeply preferential and open for interpret within different linguistic context

2021-11-10 15:56 UTC, iokpala commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-${var.env}"
With regards to this.. I misplaced the variables and had a session with Pat, where he pointed me in the right direction.. I have since reverted this change back.

2021-11-10 15:59 UTC, iokpala commented on aws/performance-test/s3.tf
> -  billing_tag_value = "notification-canada-ca-${var.env}"
Yes this change has been reverted

2021-11-10 19:40 UTC, jimleroyer commented on aws/performance-test/lambda.tf
> +      LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID       = var.load_test_email_with_link_template_id
Alright

2021-11-10 19:49 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  description = "This helps identify performance test domain."
Yeah it might be preferential, I try to favor short and concise message/doc. The interpretation and context is quite limited to Terraform and environment variable handling here though.

2021-11-10 19:49 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-staging"
Can we just try it?

2021-11-10 20:26 UTC, iokpala commented on aws/performance-test/variables.tf
> +  description = "This helps identify performance test domain."
This change has been made to reflect "Identifies"

2021-11-10 20:27 UTC, jimleroyer commented on aws/performance-test/variables.tf
> +  default     = "notify-performance-test-results-staging"
oh wrong thread, sorry

2021-11-10 20:36 UTC, jimleroyer approved these changes

2021-11-10 20:46 UTC, patheard approved these changes
🎉

2021-11-10 20:47 UTC, merged