Initial performance test ECS code
cds-snc/notification-terraform pull request #323
Opened 2021-11-24 16:30 UTC by sastels

# Summary | Résumé

There is code here. It does not crash terraform plan on my laptop.

# Test instructions | Instructions pour tester la modification

# Help requested | Aide requise

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

getting it working (and with a locust image)

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-11-24 17:17 UTC, jimleroyer commented on aws/performance-test/ecs.tf
> +  name = "performanceTestCluster"
I'd vote for lower-dash-names for infrastructure component names.

2021-11-24 17:18 UTC, jimleroyer commented on aws/performance-test/ecs.tf
> +  }
We'd need environment variables defined such as in the screenshots I shared in Slack yesterday evening.

2021-11-24 17:19 UTC, jimleroyer commented on aws/performance-test/iam.tf
> +resource "aws_iam_role" "perf_test_ecs_task" {
This is super useful for me to add these in the manual tests. 👍

2021-11-24 18:37 UTC, sastels commented on aws/performance-test/ecs.tf
> +  }
I added defaults for these
https://github.com/cds-snc/notification-terraform/pull/323/files#diff-593810ca1ac9ea004f6b100fa8417d1b76765e74c2f2dcea18e87b57d7323385R61-R68
We're probably never going to change these so I think the main benefit to not just hard coding them everywhere is to reduce the chance of typos.  Though maybe we want to set the values in the terragrunt file.

2021-11-24 19:00 UTC, jimleroyer commented on aws/performance-test/ecs.tf
> +  }
The environment expects header, phone numbers, template ids, etc... in env vars I think. You will see it in the SS I referred to [over here](https://gcdigital.slack.com/archives/G01EDRQQKTR/p1637711503046400?thread_ts=1637707719.040900&cid=G01EDRQQKTR).

2021-11-25 18:28 UTC, patheard commented on aws/performance-test/cloudwatch.tf
> +# }
minor nit: I'd vote for not committing commented out code.

2021-11-25 18:31 UTC, patheard commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +[
I think you'll want to add your increase to the ECS container's `ulimit` in this task definition:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-resource-limits

2021-11-25 18:33 UTC, sastels commented on aws/performance-test/cloudwatch.tf
> +# }
opps yep forgot to clean up all the files 👍

2021-11-25 18:33 UTC, patheard commented on aws/performance-test/variables.tf
>  variable "test_auth_header" {
If you mark this as `sensitive = true` it will never output its value in a Terraform plan.

2021-11-25 18:35 UTC, patheard commented on aws/performance-test/cloudwatch.tf
> +resource "aws_cloudwatch_log_metric_filter" "ecs_task_error_metric" {
Out of curiosity, do you plan to look at this metric?  I've used it in the past when I need to create alarms based on ECS task errors.  

If you're not planning to alarm on errors, you could also remove the metric (but there's no harm in keeping it - metric filters are cheap).

2021-11-25 18:36 UTC, patheard commented on aws/performance-test/variables.tf
> -  default     = "cron(0 0 * * ? *)"
I like that you've removed all the `default` values 👍🏻   Makes it more explicit as to where a variable value is coming from.

2021-11-25 18:37 UTC, patheard commented on env/staging/performance-test/terragrunt.hcl
> +  env                                         = "staging"
You should just be able to use the common `var.env` that gets its value from:
https://github.com/cds-snc/notification-terraform/blob/main/env/staging/env_vars.hcl#L5

2021-11-25 18:51 UTC, patheard commented on aws/performance-test/container_execution_role.tf
> +resource "aws_iam_role" "server_metrics_container_execution_role" {
minor nit: I'd change this resource name to something like `perf_test_container_execution_role`

2021-11-25 19:00 UTC, patheard requested changes
Alrighty - looking good but had some comments around your container and task execution roles and the policies that have been attached.

Also, IAM is hard.

2021-11-25 19:00 UTC, patheard commented on aws/performance-test/container_execution_role.tf
> +resource "aws_iam_role" "server_metrics_container_execution_role" {
actually, I don't think you need this since you're using the `aws_iam_role.container_execution_role` above as the container execution role.

2021-11-25 19:00 UTC, patheard commented on aws/performance-test/iam.tf
> +}
You shouldn't need this policy attachment on your task execution role.

2021-11-25 19:00 UTC, patheard commented on aws/performance-test/iam.tf
> +}
Same comment - I don't think this policy attachment is needed for your task role either.

2021-11-25 19:00 UTC, patheard commented on aws/performance-test/iam.tf
> +}
You can get rid of this policy document as well since only the container execution role needs the ECR image pull, which it gets from the `AmazonEC2ContainerServiceforEC2Role` managed policy.

2021-11-25 19:00 UTC, patheard commented on aws/performance-test/container_execution_role.tf
> +data "aws_iam_policy" "ec2_container_service" {
If you want, you can get rid of this data element and attach the managed policies like so (just for consistency with how you've done it for the Task execution role):
```hcl
resource "aws_iam_role_policy_attachment" "ce_cs" {
  role       = aws_iam_role.container_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
}
```

2021-11-25 19:08 UTC, patheard commented on aws/performance-test/container_execution_role.tf
> +}
It looks like GitHub ate my comment - you should be able to get rid of this role since you're using `aws_iam_role.container_execution_role` as the container execution role.

2021-11-25 20:30 UTC, patheard commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${PERF_TEST_AWS_S3_BUCKET}"
Missed this until you question on Slack.  The `environment` entries should all be `value`:
```json
{
   "name": "PERF_TEST_AWS_S3_BUCKET",
   "value": "${PERF_TEST_AWS_S3_BUCKET}"
} 
```

2021-11-25 20:31 UTC, patheard commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +      },
This will only work if `PERF_TEST_PHONE_NUMBER` is the ARN of a secret.

2021-11-25 20:33 UTC, sastels commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${PERF_TEST_AWS_S3_BUCKET}"
This is all starting to make some sort of sense 👍

2021-11-25 20:33 UTC, sastels commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +      },
yeah, those are coming from GitHub secrets so should all be up in the environment section

2021-11-25 23:04 UTC, jimleroyer commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "hardLimit": 16384
We know now we need at least `65536` for the `hardLimit` value.

2021-11-26 14:34 UTC, jimleroyer approved these changes
Let's do it! 🥼

2021-11-26 15:14 UTC, CalvinRodo approved these changes
Only one comment, that should be addressed.

2021-11-26 15:14 UTC, CalvinRodo commented on aws/performance-test/iam.tf
> +    }
The Task Execution Role shouldn't need this.

2021-11-26 16:22 UTC, patheard approved these changes

2021-11-26 17:03 UTC, merged