add vpc
cds-snc/notification-terraform pull request #325
Opened 2021-11-26 19:03 UTC by sastels

# Summary | Résumé

Fix the apply

# Test instructions | Instructions pour tester la modification

# Help requested | Aide requise

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-11-26 20:45 UTC, iokpala approved these changes
LGTM

2021-11-26 21:01 UTC, patheard commented on env/staging/performance-test/terragrunt.hcl
> +  vpc_id                                      = dependency.common.outputs.vpc_id
Can you add this to the mock outputs above for the dependency as well.

2021-11-26 21:03 UTC, patheard commented on aws/performance-test/ecs.tf
> +    test_auth_header_arn       = aws_secretsmanager_secret.test_auth_header.arn
This should be the `aws_secretsmanager_secret_version` resource for each secret I believe.

Also, minor nit: I would keep with the same UPPERCASE style that you used for the var names above (but this is really just a tabs v. spaces style preference and won't change behaviour).

2021-11-26 21:18 UTC, sastels commented on aws/performance-test/ecs.tf
> +    test_auth_header_arn       = aws_secretsmanager_secret.test_auth_header.arn
I think it's just the secret's arn? looking at
https://github.com/cds-snc/covid-alert-metrics-terraform/blob/f0d566597aff31150c9c6e720bd4d503f7336ed9/aws/ecs/server_metrics_etl.tf#L28

2021-11-26 21:32 UTC, jimleroyer commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${TEST_AUTH_HEADER_ARN}"
Let's keep the same prefix as other related variable with `PERF_TEST...` if possible.

2021-11-26 21:32 UTC, jimleroyer commented on aws/performance-test/ecs.tf
> +    TEST_AUTH_HEADER_ARN       = aws_secretsmanager_secret.test_auth_header.arn
Same here with `PERF_TEST...` and `perf_test_auth_header`.

2021-11-26 21:33 UTC, jimleroyer commented on aws/performance-test/security_group.tf
> +  vpc_id      = var.vpc_id
Oh yeah, this was necessary for the manual setup. 👍

2021-11-26 21:44 UTC, patheard commented on aws/performance-test/ecs.tf
> +    test_auth_header_arn       = aws_secretsmanager_secret.test_auth_header.arn
Also on the topic of secrets, you'll need to add an IAM policy to your [ECS task execution role](https://github.com/cds-snc/notification-terraform/blob/main/aws/performance-test/iam.tf#L1-L7) that allows it to read those secret values.

It'll look something like so:
https://github.com/cds-snc/gc-articles/blob/main/infrastructure/terragrunt/aws/ecs/iam.tf#L69-L97

2021-11-26 21:45 UTC, patheard requested changes
Looks good!  The only thing that you're missing is the IAM policy that'll let the ECS task get the secret values.

2021-11-27 14:02 UTC, patheard commented on aws/performance-test/ecs.tf
> +    test_auth_header_arn       = aws_secretsmanager_secret.test_auth_header.arn
@sastels I was curious and dug into it more - the reason it works with either `aws_secretsmanager_secret_version.arn` or `aws_secretsmanager_secret.arn` is because both return the same ARN:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_version#arn

And random tidbit, because I was still curious, the way we've been creating/managing `aws_secretsmanager_secret_version` resources is without a [`version_stages` value](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_version#version_stages) (so we get a default `AWSCURRENT` as its label).  When you reference a secret by its ARN, the value returned is the secret version with this `AWSCURRENT` label.

2021-11-29 16:10 UTC, sastels commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${TEST_AUTH_HEADER_ARN}"
The image expects `TEST_AUTH_HEADER_ARN` so for now I'll give it both `TEST_AUTH_HEADER_ARN` and `PERF_TEST_AUTH_HEADER_ARN`.

2021-11-29 16:28 UTC, sastels commented on aws/performance-test/ecs.tf
> +    test_auth_header_arn       = aws_secretsmanager_secret.test_auth_header.arn
Added https://github.com/cds-snc/notification-terraform/pull/325/files#diff-7c9a5642c257361dcf4142aafb573b899cc1e319a6ea09e852fef477c95e3ba2R28-R53

2021-11-29 16:36 UTC, jimleroyer commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${TEST_AUTH_HEADER_ARN}"
Ok good thinking to support both. Here is the PR to rename the variable:
https://github.com/cds-snc/notification-api/pull/1409/files

2021-11-29 16:43 UTC, sastels commented on aws/performance-test/container_definitions/perf_test.json.tmpl
> +        "valueFrom": "${TEST_AUTH_HEADER_ARN}"
👍  I'll just delete `TEST_AUTH_HEADER`, we can just upload a new image with your PR changes.

2021-11-29 18:10 UTC, patheard approved these changes
Looking good Steve 🎉

2021-11-29 18:17 UTC, merged