Add heartbeat lambda
cds-snc/notification-terraform pull request #340
Opened 2021-12-06 19:35 UTC by jzbahrai

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

# Help requested | Aide requise

> Things that you (the submitter) want reviewers to pay very close attention to
> when they review this.

---

> Éléments auxquels vous (le demandeur) souhaitez que les réviseurs prêtent
> attention lorsqu’ils examineront votre demande.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> Are there any related issues or tangent features you consider out of scope for
> this issue that could be addressed in the future?

---

> Y a-t-il des questions connexes que vous considérez hors sujet et qui
> pourraient être abordées plus tard?

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux
      langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce
      que ça devrait être divisé en de plus petites demandes de tirage (« pull
      requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2021-12-06 20:16 UTC, jzbahrai commented on aws/heartbeat/lambda.tf
> +  schedule_expression = var.schedule_expression
I couldnt figure out where this should be set?

2021-12-06 20:56 UTC, jzbahrai commented on aws/heartbeat/variables.tf
> +  sensitive   = true
change sensitive

2021-12-06 21:05 UTC, sastels requested changes
You also need to add then new variables as well as a heartbeat section to the github actions:
terragrunt_plan_staging.yml
terragrunt_plan_production.yml
merge_to_main_staging.yml
merge_to_main_production.yml

2021-12-06 21:57 UTC, jzbahrai commented
@sastels yup done in this PR: https://github.com/cds-snc/notification-terraform/pull/338
also made the updates we talked about.

2021-12-06 23:27 UTC, jimleroyer commented on env/staging/heartbeat/terragrunt.hcl
> +}
We could add the production values right away as the values are predictable.

2021-12-07 15:57 UTC, patheard commented on aws/heartbeat/ecr.tf
> +  #tfsec:ignore:AWS078
You should be able to remove this comment since the warning will get suppressed below by this one:
```hcl
image_tag_mutability = "MUTABLE" #tfsec:ignore:AWS078
```

2021-12-07 15:58 UTC, patheard commented on aws/heartbeat/lambda.tf
> +  }
If you're always using the `latest` tag for the image, you can remove this lifecycle rule.  Normally you'd only have an ignore on the `image_uri` if it was being updated by another process outside of Terraform.

2021-12-07 16:00 UTC, patheard commented on aws/heartbeat/lambda.tf
> +resource "aws_lambda_function" "heartbeat" {
We have a Terraform Lambda module that'll take care of a lot of the setup for you here:
https://github.com/cds-snc/terraform-modules/tree/main/lambda

If you want to see an example of it in action, we've got one in the [ScanFiles `lambda.tf`](https://github.com/cds-snc/scan-files/blob/main/terragrunt/aws/api/lambda.tf#L1-L32).

Also happy to help you get it up and running if you get stuck!

2021-12-07 16:02 UTC, patheard commented on aws/heartbeat/lambda.tf
> +}
I think you can get away without using an `aws_lambda_alias` here.  Usually this is for when you want to maintain multiple versions of a Lambda function and switch easily between them.

2021-12-07 16:03 UTC, patheard commented on env/staging/heartbeat/terragrunt.hcl
> +  source = "../../../aws/heartbeat"
This needs a double slash to help resolve the path:
```hcl
source = "../../../aws//heartbeat"
```

2021-12-07 16:07 UTC, patheard commented on aws/heartbeat/lambda.tf
> +  arn  = aws_lambda_function.heartbeat-test.arn
I think this should just be `aws_lambda_function.heartbeat.arn` to reference the Lambda function.

2021-12-07 16:08 UTC, patheard requested changes
Alrighty, added some fixes/comments, but overall it's a good start!

2021-12-07 16:13 UTC, jzbahrai commented on env/staging/heartbeat/terragrunt.hcl
> +  source = "../../../aws/heartbeat"
I originally put it as that but was confused about the double slash.

2021-12-07 16:14 UTC, jzbahrai commented on aws/heartbeat/lambda.tf
> +resource "aws_lambda_function" "heartbeat" {
ya I think I am going to need help with that hahaha. Will set up something.

2021-12-07 16:21 UTC, patheard commented on env/staging/heartbeat/terragrunt.hcl
> +  source = "../../../aws/heartbeat"
Totally agree - it is confusing.  The reason behind it is related to how Terraform references modules in sub-directories:
https://www.terraform.io/docs/language/modules/sources.html#modules-in-package-sub-directories

Terragrunt is just using the same rules as Terraform and uses the `//` to indicate that everything before it (`../../../aws`) is the module source and the big after is a sub-directory within that module.

2021-12-08 15:52 UTC, jzbahrai commented on env/staging/heartbeat/terragrunt.hcl
> +}
done

2021-12-08 15:53 UTC, jzbahrai commented on aws/heartbeat/ecr.tf
> +  #tfsec:ignore:AWS078
done

2021-12-08 15:53 UTC, jzbahrai commented on aws/heartbeat/lambda.tf
> +  }
done

2021-12-08 15:53 UTC, jzbahrai commented on aws/heartbeat/lambda.tf
> +resource "aws_cloudwatch_event_rule" "heartbeat-testing" {
done

2021-12-08 15:53 UTC, jzbahrai commented on env/staging/heartbeat/terragrunt.hcl
> +  source = "../../../aws/heartbeat"
done.

2021-12-08 15:53 UTC, jzbahrai commented on aws/heartbeat/lambda.tf
> +  arn  = aws_lambda_function.heartbeat-test.arn
changed.

2021-12-08 16:58 UTC, patheard commented on env/production/heartbeat/terragrunt.hcl
> +  billing_tag_value                           = "notification-canada-ca-production"
You'll need to define this variable in your `aws/heartbeat/variables.tf`.  That's why the `terraform plan` is complaining.

2021-12-08 16:58 UTC, patheard commented on env/production/heartbeat/terragrunt.hcl
> +  billing_tag_key                             = "CostCenter"
I think you can get rid of this - I don't see it being used anywhere.

2021-12-08 16:59 UTC, patheard commented on env/staging/heartbeat/terragrunt.hcl
> +  billing_tag_value                           = "notification-canada-ca-staging"
Same comments as the prod `terragrunt.hcl`

2021-12-08 17:02 UTC, patheard requested changes
Just a few gotchas with variables that need to be defined.

You'll also need to update the merge workflows with a block to `terraform apply` the heartbeat lambda changes.  Something like so for each one:

* [Prod](https://github.com/cds-snc/notification-terraform/blob/main/.github/workflows/merge_to_main_production.yml#L117-L120)
* [Staging](https://github.com/cds-snc/notification-terraform/blob/main/.github/workflows/merge_to_main_staging.yml#L125-L128)

2021-12-08 17:16 UTC, jzbahrai commented
@patheard made all the changes :) thank you for the thorough review.

2021-12-08 17:27 UTC, sastels commented
> @sastels yup done in this PR: #338
> also made the updates we talked about.

Oh, awesome! 🙃

2021-12-08 17:33 UTC, sastels commented
In the terraform plan I see
```
  + "heartbeat_template_id" = "\"\""
```
Is the template I’d not being set correctly somewhere?

2021-12-08 18:10 UTC, patheard commented
> In the terraform plan I see
> 
> ```
>   + "heartbeat_template_id" = "\"\""
> ```
> 
> Is the template I’d not being set correctly somewhere?

Good catch @sastels.  Looks like the value is coming from a [GitHub secret](https://github.com/cds-snc/notification-terraform/blob/main/.github/workflows/merge_to_main_staging.yml#L24).

2021-12-08 18:12 UTC, patheard approved these changes
I'd say it's good to merge once that `heartbeat_template_id` is figured out!

2021-12-08 18:27 UTC, sastels approved these changes
Let's try this out!

2021-12-08 18:39 UTC, merged