Add alarms for expired inflights
cds-snc/notification-terraform pull request #528
Opened 2022-09-01 20:55 UTC by jzbahrai

# Summary | Résumé

Add alarms for expired inflights.

2022-09-01 21:00 UTC, jzbahrai commented
I didn't updated terragrunt/production.hcl as I only want to test these alarms on staging first. Is this correct?

2022-09-02 19:02 UTC, sastels commented on aws/common/cloudwatch_alarms.tf
> +  alarm_description   = "Email inflights are expiring at > ${var.alarm_warning_expired_sms_created_threshold} for 5 minutes"
`alarm_warning_expired_sms_created_threshold` -> `alarm_warning_expired_email_created_threshold`

2022-09-02 19:05 UTC, sastels requested changes
LGTM - minor comment on the alarm string, and update those google docs

2022-09-06 14:48 UTC, jzbahrai commented on aws/common/cloudwatch_alarms.tf
> +  alarm_description   = "Email inflights are expiring at > ${var.alarm_warning_expired_sms_created_threshold} for 5 minutes"
done

2022-09-06 21:09 UTC, sastels commented on aws/common/cloudwatch_alarms.tf
> +  alarm_actions = [aws_sns_topic.notification-canada-ca-alert-critical.arn]
oh, just noticed, this should be 
```
  alarm_actions = [aws_sns_topic.notification-canada-ca-alert-warning.arn]
```

2022-09-06 21:09 UTC, sastels commented on aws/common/cloudwatch_alarms.tf
> +  ok_actions    = [aws_sns_topic.notification-canada-ca-alert-ok.arn]
and we don't need the `ok_action` for the warning

2022-09-06 21:10 UTC, sastels commented on aws/common/cloudwatch_alarms.tf
> +  ok_actions    = [aws_sns_topic.notification-canada-ca-alert-ok.arn]
Also here with ` alarm_actions = [aws_sns_topic.notification-canada-ca-alert-warning.arn]` and no warning

2022-09-06 21:14 UTC, sastels approved these changes
:shipit: after adjusting those alarm actions!

2022-09-06 21:18 UTC, jzbahrai commented on aws/common/cloudwatch_alarms.tf
> +  alarm_actions = [aws_sns_topic.notification-canada-ca-alert-critical.arn]
done

2022-09-06 21:18 UTC, jzbahrai commented on aws/common/cloudwatch_alarms.tf
> +  ok_actions    = [aws_sns_topic.notification-canada-ca-alert-ok.arn]
done

2022-09-06 21:18 UTC, sastels commented on aws/common/cloudwatch_alarms.tf
> +  alarm_actions = [aws_sns_topic.notification-canada-ca-alert-critical.arn]
otherwise I assume ops genie will page on every celery error. I'm not on call for a couple weeks, though 😂

2022-09-16 19:28 UTC, jimleroyer commented
@jzbahrai Thanks for adding these and making us more aware. I was wondering if we saw cases where the expiration got past the 5 minutes? I am asking as I was wondering if the auto move of the messages on the redis list from inflight to inbox would reset the metrics and prevent us from detecting expired inflights? 🤔

2022-09-16 19:54 UTC, jzbahrai commented
<img width="1433" alt="Screen Shot 2022-09-16 at 3 54 25 PM" src="https://user-images.githubusercontent.com/8869623/190720815-b3c30dcd-8df2-49a0-b12a-c3ee21290f9c.png">

2022-09-20 13:12 UTC, merged