Initial blazer commit
cds-snc/notification-terraform pull request #553
Opened 2022-10-14 14:57 UTC by jzbahrai

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2022-10-14 15:26 UTC, jzbahrai commented
I ran the apply locally and got the following so in theory it should have worked...
```aws_iam_policy.blazer_execution_role_policy: Creating...
aws_iam_role.blazer_execution_role: Creating...
aws_iam_policy.blazer_execution_role_policy: Creation complete after 1s [id=arn:aws:iam::239043911459:policy/blazer_execution_role_policy]
aws_iam_role.blazer_execution_role: Creation complete after 2s [id=blazer_execution_role]
aws_iam_role_policy_attachment.ce_cs: Creating...
aws_iam_role_policy_attachment.blazer_execution_role_actions: Creating...
aws_ecs_task_definition.blazer: Creating...
aws_ecs_task_definition.blazer: Creation complete after 0s [id=blazer]
aws_ecs_service.blazer: Creating...
aws_iam_role_policy_attachment.blazer_execution_role_actions: Creation complete after 0s [id=blazer_execution_role-20221014152515199500000002]
aws_iam_role_policy_attachment.ce_cs: Creation complete after 0s [id=blazer_execution_role-20221014152515196600000001]
aws_ecs_service.blazer: Creation complete after 1s [id=arn:aws:ecs:ca-central-1:239043911459:service/blazer/blazer]
```

2022-10-17 18:55 UTC, CalvinRodo requested changes
See changes for work to do to get this working, just the stuff we went over during our chats.

2022-10-17 18:55 UTC, CalvinRodo commented on aws/database-tools/securitygroups.tf
> +    }
Instead of allowing egress to the subnet this needs to allow egress to the Security Group that the RDS instance is running in (the EKS Security Group) and then also modify the security group the RDS instance is running in to allow ingress from tis security group

Alternatively you could keep it as is and allow ingress from the private subnet to the EKS Security Group but that is probably not the best idea from a security point of view.

2022-10-17 18:55 UTC, CalvinRodo commented on aws/database-tools/container_execution_role.tf
> +}
This needs to be attached to `aws_iam_role.blazer_ecs_task.name` instead of `aws_iam_role.blazer_execution_role.name`

2022-10-17 20:28 UTC, jzbahrai commented on aws/database-tools/container_execution_role.tf
> +}
done please see commit [4c9e20d](https://github.com/cds-snc/notification-terraform/pull/553/commits/4c9e20d272eae76e32de7880af374098c7312417)

2022-10-17 20:30 UTC, jzbahrai commented on aws/database-tools/securitygroups.tf
> +    }
the egress is added in the first commit [4c9e20d](https://github.com/cds-snc/notification-terraform/pull/553/commits/4c9e20d272eae76e32de7880af374098c7312417)

the ingress for eks is added here: [d8e62ac](https://github.com/cds-snc/notification-terraform/pull/553/commits/d8e62acab50983063165cdcff417e3a13c93d8af)

The ingress causes a circular dependency - cause now EKS is dependent on database-tools security group, and vice versa. I know we did it through clickops - but I am unsure what I am missing here.

2022-10-17 20:32 UTC, CalvinRodo commented on aws/database-tools/securitygroups.tf
> +  }
This can be removed as there is no need for egress to the subnet if you are also allowing Egress to the eks security group

2022-10-18 17:31 UTC, jzbahrai commented on aws/database-tools/securitygroups.tf
> +resource "aws_network_interface_sg_attachment" "sg_attachment" {
this seems to be how I would attach the security group to the blazer task?
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface_sg_attachment

but I am unsure what the `network_interface_id` should be in this instance

2022-10-18 17:32 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress" {
so I had to split this up due to the circular dependency. 
After I split the resource up - this is the error I get:
```
 Error: Incorrect attribute value type
│
│   on securitygroups.tf line 77, in resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress":
│   77:   source_security_group_id = [aws_security_group.blazer.id]
│     ├────────────────
│     │ aws_security_group.blazer.id will be known only after apply
│
│ Inappropriate value for attribute "source_security_group_id": string
│ required.
```
is there anything I can do in this case for the plan?

2022-10-18 17:33 UTC, jzbahrai commented on env/staging/database-tools/terragrunt.hcl
> +  database-tools-securitygroup = dependency.eks.outputs.database-tools-securitygroup
so I get an error when running the plan 
```
ERRO[0014] /Users/jumana/Notify/notification-terraform/env/staging/database-tools/terragrunt.hcl:43,56-85: Unsupported attribute; This object does not have an attribute named "database-tools-securitygroup".
```
I have set up an output from eks for the security group. Am I missing something here?

2022-10-18 17:49 UTC, sastels commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress" {
it's just saying it wants `aws_security_group.blazer.id` instead of the list `[aws_security_group.blazer.id]` I think.

2022-10-18 18:12 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress" {
🤦🏽 changed it and it worked 🙇🏽

2022-10-18 19:57 UTC, patheard commented on aws/database-tools/blazer.tf
> +      "image" : "ankane/blazer:latest",
Minor suggestion to pin this to a specific image tag or SHA.  It'll help avoid any unexpected upgrades in the future.

2022-10-18 20:08 UTC, patheard commented on aws/database-tools/securitygroups.tf
> +resource "aws_network_interface_sg_attachment" "sg_attachment" {
I don't think you need this resource.  The `var.database-tools-securitygroup` security group is getting attached to the task by the `aws_ecs_service` resources' `network_configuration` block:
```hcl
resource "aws_ecs_service" "blazer" {
  name                   = "blazer"
  cluster                = aws_ecs_cluster.blazer.id
  task_definition        = aws_ecs_task_definition.blazer.arn
  desired_count          = 1
  launch_type            = "FARGATE"
  enable_execute_command = true

  network_configuration {
    security_groups = [var.database-tools-securitygroup]
    subnets         = var.vpc_private_subnets
  }
}
```

We haven't needed to use `aws_network_interface_sg_attachment` in any of our other Terraform, but I may also be misunderstanding what you're trying to do here.

2022-10-18 20:37 UTC, patheard commented on aws/database-tools/variables.tf
> +  type = list(any)
minor nit: could you add `description`'s to these new variables - it is for the benefit of future-Pat 😅

2022-10-18 20:37 UTC, patheard commented on aws/database-tools/variables.tf
> +  sensitive   = true
This doesn't need to be sensitive.

2022-10-18 20:43 UTC, patheard commented on aws/eks/securitygroups.tf
> +  }
I don't think this egress is needed by Blazer.  Since the security group is stateful, the incoming connection from the SSM session will be allowed out.

2022-10-18 20:57 UTC, patheard commented on aws/eks/securitygroups.tf
> +  }
Actually, nvm - this is possibly for pulling the Blazer docker image.  We could tighten this down by putting that Blazer image in an ECR in this account, creating a VPC PrivateLink to ECR and giving the task security group the ability to use that PrivateLink.

2022-10-18 21:03 UTC, patheard commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress" {
I don't think you need this either. The ALB shouldn't need to allow `5432` ingress requests.

2022-10-18 21:04 UTC, patheard commented on aws/database-tools/rds_proxy.tf
> +locals {
nit: could you rename this file since it's not an RDS proxy.

2022-10-18 21:05 UTC, patheard commented on aws/database-tools/rds.tf
> +  engine_version      = "11.9"
Could you bump this to the latest Postgres engine available.

2022-10-18 21:15 UTC, patheard commented on aws/database-tools/rds.tf
> +  engine              = "aurora-postgresql"
If you just set the engine version to `postgresql` you'll be able to use the smaller `t3.micro` instances.

2022-10-18 21:16 UTC, patheard commented on aws/database-tools/rds.tf
> +}
We can skip these for this little tools DB instance.

2022-10-18 22:59 UTC, patheard commented on aws/database-tools/rds.tf
> +  security_group_names = [var.database-tools-securitygroup]
We should switch this to using [`vpc_security_group_ids`] (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#vpc_security_group_ids) instead and create our own DB security group.  I can help get this going tomorrow.

2022-10-19 18:26 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +    security_groups = [data.aws_security_group.eks-securitygroup-rds, aws_security_group.database-tools-db-securitygroup]
This fails though it takes a list: 
```
│ Error: Incorrect attribute value type
│
│   on securitygroups.tf line 75, in resource "aws_security_group" "blazer":
│   75:     security_groups = [data.aws_security_group.eks-securitygroup-rds, aws_security_group.database-tools-db-securitygroup]
│     ├────────────────
│     │ aws_security_group.database-tools-db-securitygroup is object with 13 attributes
│     │ data.aws_security_group.eks-securitygroup-rds is object with 7 attributes
│
│ Inappropriate value for attribute "security_groups": element 0: string
│ required.
```

2022-10-19 18:27 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +    security_groups = [data.aws_security_group.eks-securitygroup-rds, aws_security_group.database-tools-db-securitygroup]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#security_groups

2022-10-19 19:32 UTC, jzbahrai commented on aws/database-tools/securitygroups.tf
> +resource "aws_network_interface_sg_attachment" "sg_attachment" {
done

2022-10-19 19:32 UTC, jzbahrai commented on aws/database-tools/blazer.tf
> +      "image" : "ankane/blazer:latest",
done

2022-10-19 19:32 UTC, jzbahrai commented on aws/database-tools/variables.tf
> +  type = list(any)
done

2022-10-19 19:32 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "notification-canada-ca-alb-database-tools-ingress" {
based on the conversation I changed this to the security group that is for RDS

2022-10-19 19:33 UTC, jzbahrai commented on aws/database-tools/rds_proxy.tf
> +locals {
done

2022-10-19 19:33 UTC, jzbahrai commented on aws/database-tools/rds.tf
> +  engine_version      = "11.9"
done

2022-10-19 19:34 UTC, jzbahrai commented on aws/database-tools/rds.tf
> +  engine              = "aurora-postgresql"
done

2022-10-19 19:41 UTC, jzbahrai commented on aws/database-tools/securitygroups.tf
> +data "aws_subnet" "private_subnet" {
I dont think we need this anymore?

2022-10-19 19:42 UTC, jzbahrai commented on aws/eks/securitygroups.tf
> +resource "aws_security_group_rule" "database-tools-db-ingress" {
I had to split this out as there was circular dependency error

2022-10-19 19:43 UTC, jzbahrai commented on aws/database-tools/parameterstore.tf
> +  value = "postgres://postgres:${var.dbtools_password}@${aws_db_instance.database-tools.address}:5432"
is this the correct way to do this?  cause the resource hasn't been declared at all?
```
╷
│ Error: Reference to undeclared resource
│
│   on blazer.tf line 72, in resource "aws_ecs_task_definition" "blazer":
│   72:         "valueFrom" : "${aws_ssm_paramter.db_tools_environment_variables.arn}"
│
│ A managed resource "aws_ssm_paramter" "db_tools_environment_variables" has
│ not been declared in the root module.
╵
ERRO[0019] Terraform invocation failed in /Users/jumana/Notify/notification-terraform/env/staging/database-tools/.terragrunt-cache/eJTmRh_RVe4HG7CkukNccPsSsbo/-W3lh3rI8VFfRvtQD2cPdpT6ILw/database-tools  prefix=[/Users/jumana/Notify/notification-terraform/env/staging/database-tools]
ERRO[0019] 1 error occurred:
	* exit status 1
```

2022-10-19 19:44 UTC, jzbahrai commented on aws/database-tools/parameterstore.tf
> +resource "aws_secretsmanager_secret_version" "dbtools_database_user" {
we never reference this resource/.... I think we can remove it?

2022-10-19 19:45 UTC, jzbahrai commented on aws/database-tools/rds.tf
> +  db_subnet_group_name   = var.vpc_private_subnets[0]
I hardcoded this [0] instead of making a resource, cause this was the problem I was getting:

```
resource "aws_db_subnet_group" "database-tools-rds-subnet" {
  name       = "database-tools-rds-subnet"
  subnet_ids = [var.vpc_private_subnets[0]]

  tags = {
    Name = "My DB subnet group"
  }
}
```

```
│ Error: Incorrect attribute value type
│
│   on rds.tf line 32, in resource "aws_db_instance" "database-tools":
│   32:   db_subnet_group_name   = aws_db_subnet_group.database-tools-rds-subnet
│     ├────────────────
│     │ aws_db_subnet_group.database-tools-rds-subnet is object with 8 attributes
│
│ Inappropriate value for attribute "db_subnet_group_name": string required.
```

2022-10-20 12:59 UTC, patheard commented on aws/database-tools/parameterstore.tf
> +resource "aws_secretsmanager_secret_version" "dbtools_database_user" {
yup, should be safe to remove!  This is a leftover from the RDS proxy setup I believe.

2022-10-20 13:00 UTC, patheard commented on aws/database-tools/blazer.tf
> +        "valueFrom" : "${aws_ssm_paramter.db_tools_environment_variables.arn}"
The reason you're getting the TF plan error is a type on `aws_ssm_paramter`

2022-10-20 13:41 UTC, patheard commented on aws/database-tools/parameterstore.tf
> +  value = "postgres://postgres:${var.dbtools_password}@${aws_db_instance.database-tools.address}:5432"
Yup, you've just got a typo where you're referencing this resource with a missing `e` in `aws_ssm_paramter`.

2022-10-20 13:54 UTC, patheard commented on aws/database-tools/rds.tf
> +  db_subnet_group_name   = var.vpc_private_subnets[0]
You can fix it by passing in the subnet group name like so:
```hcl
db_subnet_group_name   = aws_db_subnet_group.database-tools-rds-subnet.name
```

There are very few cases where Terraform expects a resource reference - usually it wants an attribute from a resource reference.

2022-10-20 15:13 UTC, patheard commented on aws/eks/securitygroups.tf
> +    security_groups = [data.aws_security_group.eks-securitygroup-rds, aws_security_group.database-tools-db-securitygroup]
You just need to pass in the `id` attribute for each of them and that should fix up the problem:
```hcl
security_groups = [
   data.aws_security_group.eks-securitygroup-rds.id, 
   aws_security_group.database-tools-db-securitygroup.id
]
```

2022-10-20 15:17 UTC, patheard commented on aws/eks/securitygroups.tf
> +  }
You can get rid of both of these since the database only needs to allow the Blazer security group access which you're taking care of below with `aws_security_group_rule.database-tools-db-ingress`.

2022-10-20 15:17 UTC, patheard commented on aws/eks/securitygroups.tf
> +  security_group_id        = data.aws_security_group.eks-securitygroup-rds
Same comment that these need to be `id` attributes of the resources.

2022-10-20 15:18 UTC, patheard commented on aws/database-tools/securitygroups.tf
> +data "aws_subnet" "private_subnet" {
Yup, you should be able to delete this.

2022-10-20 15:19 UTC, patheard commented on aws/eks/outputs.tf
> +}
You're likely going to want the `id` attribute for both of these instead of the `arn`.  Usually when you specify security groups on other resources it's using the `id`.

2022-10-20 19:48 UTC, jzbahrai commented
ok merging this manually cause of some tfvars local issue.

2022-10-20 19:48 UTC, merged