Lambda for google cidr
cds-snc/notification-terraform pull request #582
Opened 2022-11-17 20:10 UTC by jzbahrai

# Summary | Résumé

Lambda for google cidr

2022-11-17 20:14 UTC, jzbahrai commented on env/staging/lambda-google-cidr/terragrunt.hcl
> +  google_cidr_schedule_expression    = "rate(5 minutes)"
ill change this after, this is so we can test atm

2022-11-17 20:14 UTC, patheard commented on aws/lambda-google-cidr/lambda.tf
> +  source                 = "github.com/cds-snc/terraform-modules?ref=v0.0.45//lambda"
Can you change `v0.0.45` to the latest tag release from the terraform-modules repo.

2022-11-17 22:56 UTC, patheard requested changes
Thanks for taking care of this PR!

A few tweaks to add:
1. Can you create the [managed prefix list](https://github.com/cds-snc/notification-terraform/blob/feat/google-service-ip-prefix-list/aws/eks/securitygroups.tf#L70-L90) for the Google CIDRs and associate it with the Blazer security group.
2. We'll also need a [custom IAM policy](https://github.com/cds-snc/notification-terraform/blob/feat/google-service-ip-prefix-list/aws/eks/securitygroups.tf#L70-L90) added to the lambda function that allows it to manage the prefix list.

2022-11-19 16:02 UTC, patheard commented on aws/lambda-google-cidr/lambda.tf
> +}
This is exactly right for how normally create an IAM role + policies but for our `lambda` module it's done a little differently to you can delete all these resources.

2022-11-19 16:04 UTC, patheard commented on aws/lambda-google-cidr/lambda.tf
> +data "aws_iam_policy_document" "google_cidrs" {
You just need to specify this element as a custom policy to attach to the lambda func module:
```hcl
policies = [
  data. aws_iam_policy_document.google_cidrs.json
]
```
Here's an example of how we're doing it in another project:
https://github.com/cds-snc/scan-files/blob/main/terragrunt/aws/api/lambda.tf#L29-L33

2022-11-19 21:55 UTC, patheard commented on aws/lambda-google-cidr/lambda.tf
> +  }
You can remove this since it gets created for us by the `lambda` module.

2022-11-19 21:56 UTC, patheard commented on aws/lambda-google-cidr/lambda.tf
> +}
You can remove this since the `lambda` module creates it as well.

2022-11-21 14:26 UTC, patheard commented
Something else I just noticed - could you change the Blazer ECR to `MUTABLE` as well:
https://github.com/cds-snc/notification-terraform/blob/main/aws/database-tools/ecr.tf#L3

2022-11-21 15:49 UTC, jzbahrai commented on aws/lambda-google-cidr/lambda.tf
> +}
done

2022-11-21 15:50 UTC, jzbahrai commented on aws/lambda-google-cidr/lambda.tf
> +}
i removed these 4 resources

2022-11-21 15:50 UTC, jzbahrai commented on aws/lambda-google-cidr/lambda.tf
> +data "aws_iam_policy_document" "google_cidrs" {
done

2022-11-21 15:50 UTC, jzbahrai commented on aws/lambda-google-cidr/lambda.tf
> +  }
i removed this one statement but kept the rest

2022-11-21 15:59 UTC, patheard approved these changes

2022-11-21 16:03 UTC, merged