Edit IAM permissions for new relic user
cds-snc/notification-terraform pull request #703
Opened 2023-04-04 17:58 UTC by jzbahrai

# Summary | Résumé

Edit the permissions for new relic.

2023-04-04 19:44 UTC, ben851 commented
This looks good, although I'm concerned as to how this is currently working in both prod and staging without these permissions assigned to the policy... Unless there is a global policy that was done via clickops at some point. Lets try it in staging to see how it goes.

2023-04-04 19:44 UTC, jimleroyer commented on aws/lambda-api/iam.tf
> +      "lambda:ListEventSourceMappings"
Is this the right place to add these? @ben851 indicated that the actions should be applied on `*` resources. Would the the new relic key resource need to do these actions? I might be misunderstanding something, iam is always some black magic to me.

2023-04-04 19:49 UTC, ben851 commented on aws/lambda-api/iam.tf
> +      "lambda:ListEventSourceMappings"
I think this is good, it's where I had them for mine. I am going off what was here:
https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/

New Relic's doc's are a bit confusing in that this is talking about linking aws accounts but underneath it's talking about using the lambda integration...

2023-04-04 19:53 UTC, ben851 requested changes
As per my conversation with @jimleroyer, these permissions are not scoped to the secret manager ARN - they need to be scoped to all resources (*).  This can be done by simply creating a new block in data "aws_iam_policy_document" "api_policies"   adding these new values and setting the resources to *

2023-04-04 19:53 UTC, ben851 commented on aws/lambda-api/iam.tf
> +      "lambda:ListEventSourceMappings"
Ok I blew it you're 100% right Jimmy. I missed that this was assigned to the secret arn only. I will request the change

2023-04-05 12:03 UTC, ben851 approved these changes
Looks good!

2023-04-05 13:18 UTC, merged