Adding a warning for K8s node failure
cds-snc/notification-terraform pull request #705
Opened 2023-04-04 19:16 UTC by ben851

# Summary | Résumé

Creating a cloudwatch anomaly alert which will trigger if node failure occurs.  Currently set to warning while we verify that it works as expected.

2023-04-05 13:16 UTC, jimleroyer commented on aws/eks/cloudwatch_alarms.tf
> +      period      = 300
Would we have a faster alarm raised if we lower the period here?

2023-04-05 13:18 UTC, jimleroyer commented on aws/eks/cloudwatch_alarms.tf
> +    return_data = "true"
Why are we passing the pick to an anomaly detection expression from `m1` to `ad1` to the alarm threshold? Why not do `m1` to the alarm threshold directly?

2023-04-05 13:24 UTC, ben851 commented on aws/eks/cloudwatch_alarms.tf
> +    return_data = "true"
Disclaimer, I'm not 100% familiar with cloudwatch queries yet.

The way I determined how to code the query was by doing it via click-ops in my scratch environment and then exporting the query JSON, which I then transcoded to TF format. So what you see here is the way AWS built the query.

If I understand it correctly what is happening is that the m1m query is running every 5 minutes and returning a result. The AD1 query is then querying the results of M1 using the Anomaly detection algorithm to look for these anomalies across the time series of m1 results. We can't simply use the anomaly detection query as the primary query as there would be no time series in that case. 

If you see something I'm missing please let me know :)

2023-04-05 15:13 UTC, jimleroyer requested changes
Requesting change to get rid of anomaly detection and have the metric rely on the direct metric, as we do not require a trend detection (but mere existence of the failure).

2023-04-06 18:32 UTC, jimleroyer commented on aws/eks/cloudwatch_alarms.tf
> +  treat_missing_data = "notBreaching"
Yes we are learning from our previous noise. 🤝 😅

2023-04-06 18:33 UTC, jimleroyer approved these changes
LGTM! :shipit:

2023-04-06 18:36 UTC, merged