Quicksight
cds-snc/notification-terraform pull request #824
Opened 2023-06-30 17:35 UTC by sastels

# Summary | Résumé

Add AWS Quicksight

2023-07-14 18:39 UTC, ben851 requested changes
Very good first crack, just some small refinements to make

2023-07-14 18:39 UTC, ben851 commented on aws/quicksight/data_sources.tf
> +resource "aws_quicksight_data_source" "default" {
Can we change the resource name from "default" to something more meaningful? Even just "Notify"

2023-07-14 18:39 UTC, ben851 commented on aws/quicksight/data_sources.tf
> +      instance_id = "test"
What is an instance_id in this case? If it's an arbitrary value, can we sync it to var.env?

2023-07-14 18:39 UTC, ben851 commented on aws/quicksight/vpc.tf
> +  vpc_connection_id  = "example-connection-id"
this will need to be the vpc_id from the "common" outputs.

2023-07-14 18:39 UTC, ben851 commented on aws/quicksight/vpc.tf
> +  name               = "Example Connection"
Can we change this to something like "Notify VPC"

2023-07-14 19:48 UTC, sastels commented on aws/quicksight/data_sources.tf
> +      instance_id = "test"
hrm, when I was playing around before it was the `aws_db_instance` identifier. We have a cluster identifier now maybe? I'll try that...

2023-07-28 14:06 UTC, ben851 approved these changes
LGTM!

2023-08-11 17:37 UTC, merged