Setting visibility timeout for high priority email sqs
cds-snc/notification-terraform pull request #991
Opened 2023-10-26 17:24 UTC by ben851

# Summary | Résumé

Setting the high priority sqs email delay to 26 seconds to confirm with SLO while autoscaling.

# Release Instructions
**THIS RELEASE REQUIRES AN IMPORT FIRST**
terragrunt import -var-file <env.tfvars> aws_sqs_queue.eks_notification_canada_ca_priority_task_queue <sqs queue url - found in AWS Console>

# Test instructions | Instructions pour tester la modification

- Deploy tested in dev
- Smoke test staging

2023-10-26 19:52 UTC, jimleroyer approved these changes

2023-11-01 19:11 UTC, sastels requested changes
~High priority email is now being delivered through the `send-email-high` queue so we should set that one as well (setting the `priority-tasks` to 26 is also good idea, mind you)~ Done in [another PR](https://github.com/cds-snc/notification-terraform/pull/1029).

2023-11-15 14:16 UTC, sastels approved these changes

2024-01-08 14:57 UTC, ben851 commented
This was tackled in a different PR and therefore closing this.

2024-01-08 14:57 UTC, closed without merging